#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BGM_Manager

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_BGM_Manager.BP_BGM_Manager_C
// 0x0068 (0x0310 - 0x02A8)
class ABP_BGM_Manager_C final : public AActor
{
public:
	class UAudioComponent*                        Audio;                                             // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TMap<class FName, class USoundCue*>           BGM;                                               // 0x02B8(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FName                                   CurrentBGM;                                        // 0x0308(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)

public:
	void OnRep_CurrentBGM();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BGM_Manager_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BGM_Manager_C")
	}
	static class ABP_BGM_Manager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BGM_Manager_C>();
	}
};
DUMPER7_ASSERTS_ABP_BGM_Manager_C;

SDK_NAMESPACE_END
