#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FirstPersonPlayerState_Online_cLeon

#include "Basic.hpp"

#include "BP_FirstPersonPlayerState_Online_cLeon_classes.hpp"
#include "BP_FirstPersonPlayerState_Online_cLeon_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_FirstPersonPlayerState_Online_cLeon.BP_FirstPersonPlayerState_Online_cLeon_C.SetModState
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ModState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FirstPersonPlayerState_Online_cLeon_C::SetModState(bool ModState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FirstPersonPlayerState_Online_cLeon_C", "SetModState");

	Params::BP_FirstPersonPlayerState_Online_cLeon_C_SetModState Parms{};

	Parms.ModState = ModState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FirstPersonPlayerState_Online_cLeon.BP_FirstPersonPlayerState_Online_cLeon_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_FirstPersonPlayerState_Online_cLeon_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FirstPersonPlayerState_Online_cLeon_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FirstPersonPlayerState_Online_cLeon.BP_FirstPersonPlayerState_Online_cLeon_C.ExecuteUbergraph_BP_FirstPersonPlayerState_Online_cLeon
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FirstPersonPlayerState_Online_cLeon_C::ExecuteUbergraph_BP_FirstPersonPlayerState_Online_cLeon(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FirstPersonPlayerState_Online_cLeon_C", "ExecuteUbergraph_BP_FirstPersonPlayerState_Online_cLeon");

	Params::BP_FirstPersonPlayerState_Online_cLeon_C_ExecuteUbergraph_BP_FirstPersonPlayerState_Online_cLeon Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
