#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FirstPersonPlayerState_Online_cLeon

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_FirstPersonPlayerState_Online_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_FirstPersonPlayerState_Online_cLeon.BP_FirstPersonPlayerState_Online_cLeon_C
// 0x0010 (0x03C8 - 0x03B8)
class ABP_FirstPersonPlayerState_Online_cLeon_C final : public ABP_FirstPersonPlayerState_Online_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_FirstPersonPlayerState_Online_cLeon_C; // 0x03B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          ModState;                                          // 0x03C0(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void SetModState(bool ModState);
	void ReceiveBeginPlay();
	void ExecuteUbergraph_BP_FirstPersonPlayerState_Online_cLeon(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_FirstPersonPlayerState_Online_cLeon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_FirstPersonPlayerState_Online_cLeon_C")
	}
	static class ABP_FirstPersonPlayerState_Online_cLeon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FirstPersonPlayerState_Online_cLeon_C>();
	}
};
DUMPER7_ASSERTS_ABP_FirstPersonPlayerState_Online_cLeon_C;

SDK_NAMESPACE_END
