#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PlayerController_cLeon

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_FirstPersonPlayerController_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PlayerController_cLeon.BP_PlayerController_cLeon_C
// 0x0050 (0x07B8 - 0x0768)
class ABP_PlayerController_cLeon_C final : public ABP_FirstPersonPlayerController_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_PlayerController_cLeon_C;        // 0x0768(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class URuntimePaintRelayComponent*            RuntimePaintRelay;                                 // 0x0770(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UWBP_cLeonMain_C*                       MainWidget;                                        // 0x0778(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	double                                        CameraFadeValue;                                   // 0x0780(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsCanPenteration;                                  // 0x0788(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_789[0x7];                                      // 0x0789(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(bool IsCanPenteration)> CanPenterationUpdate;                      // 0x0790(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(bool Visibility)> NamePlateVisibilityChange;                       // 0x07A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          IsPlayMovie;                                       // 0x07B0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          WatchRankingVisibility;                            // 0x07B1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          GlobalNameplateVisibility;                         // 0x07B2(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void TeleportMovie();
	void ReceiveTick(float DeltaSeconds_ReceiveTick);
	void ReceiveBeginPlay();
	void OnNamePlateVisibilityChange(bool Visibility);
	void InpActEvt_Three_K2Node_InputKeyEvent_1(const struct FKey& Key);
	void InpActEvt_Six_K2Node_InputKeyEvent_0(const struct FKey& Key);
	void GetPawnCentorLocation(struct FVector* ReturnLocation);
	void Finish();
	void ExecuteUbergraph_BP_PlayerController_cLeon(int32 EntryPoint);
	void CameraReset();
	void AddMainWidgets();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PlayerController_cLeon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PlayerController_cLeon_C")
	}
	static class ABP_PlayerController_cLeon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PlayerController_cLeon_C>();
	}
};
DUMPER7_ASSERTS_ABP_PlayerController_cLeon_C;

SDK_NAMESPACE_END
