#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_LightBPGI

#include "Basic.hpp"

#include "BPI_LightBPGI_classes.hpp"
#include "BPI_LightBPGI_parameters.hpp"


SDK_NAMESPACE_START

// Function BPI_LightBPGI.BPI_LightBPGI_C.GetBPGI_Main
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UBPGI_Main_C**                    Object                                                 (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void IBPI_LightBPGI_C::GetBPGI_Main(class UBPGI_Main_C** Object)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_LightBPGI_C", "GetBPGI_Main");

	Params::BPI_LightBPGI_C_GetBPGI_Main Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (Object != nullptr)
		*Object = Parms.Object;
}


SDK_NAMESPACE_END
