#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_LightBPGI

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BPI_LightBPGI.BPI_LightBPGI_C.GetBPGI_Main
// 0x0008 (0x0008 - 0x0000)
struct BPI_LightBPGI_C_GetBPGI_Main final
{
public:
	class UBPGI_Main_C*                           Object;                                            // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_LightBPGI_C_GetBPGI_Main;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
