#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_RandomToggle

#include "Basic.hpp"

#include "WBP_RandomToggle_classes.hpp"
#include "WBP_RandomToggle_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_RandomToggle.WBP_RandomToggle_C.UpdateRandomVisibility
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_RandomToggle_C::UpdateRandomVisibility(bool State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RandomToggle_C", "UpdateRandomVisibility");

	Params::WBP_RandomToggle_C_UpdateRandomVisibility Parms{};

	Parms.State = State;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RandomToggle.WBP_RandomToggle_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime_PreConstruct                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_RandomToggle_C::PreConstruct(bool IsDesignTime_PreConstruct)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RandomToggle_C", "PreConstruct");

	Params::WBP_RandomToggle_C_PreConstruct Parms{};

	Parms.IsDesignTime_PreConstruct = IsDesignTime_PreConstruct;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RandomToggle.WBP_RandomToggle_C.ExecuteUbergraph_WBP_RandomToggle
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_RandomToggle_C::ExecuteUbergraph_WBP_RandomToggle(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RandomToggle_C", "ExecuteUbergraph_WBP_RandomToggle");

	Params::WBP_RandomToggle_C_ExecuteUbergraph_WBP_RandomToggle Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RandomToggle.WBP_RandomToggle_C.BndEvt__WBP_RandomToggle_NavButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_RandomToggle_C::BndEvt__WBP_RandomToggle_NavButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RandomToggle_C", "BndEvt__WBP_RandomToggle_NavButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
