#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_cLeonBullet

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "SlateCore_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_cLeonBullet.WBP_cLeonBullet_C.SetBulletState
// 0x0001 (0x0001 - 0x0000)
struct WBP_cLeonBullet_C_SetBulletState final
{
public:
	bool                                          State;                                             // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_cLeonBullet_C_SetBulletState;

// Function WBP_cLeonBullet.WBP_cLeonBullet_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_cLeonBullet_C_PreConstruct final
{
public:
	bool                                          IsDesignTime_PreConstruct;                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_cLeonBullet_C_PreConstruct;

// Function WBP_cLeonBullet.WBP_cLeonBullet_C.ExecuteUbergraph_WBP_cLeonBullet
// 0x0058 (0x0058 - 0x0000)
struct WBP_cLeonBullet_C_ExecuteUbergraph_WBP_cLeonBullet final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FWidgetAnimationHandle                 CallFunc_PlayAnimation_ReturnValue;                // 0x0008(0x0010)(NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_State;                          // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1A[0x2];                                       // 0x001A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x001C(0x0014)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_1;                    // 0x0030(0x0014)()
	struct FSlateColor                            K2Node_Select_Default;                             // 0x0044(0x0014)()
};
DUMPER7_ASSERTS_WBP_cLeonBullet_C_ExecuteUbergraph_WBP_cLeonBullet;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
